In [1]:
from lokigi.site import SiteProblem
import geopandas
import pandas as pd
import pickle
import imageio.v2 as imageio
from pathlib import Path
import matplotlib.pyplot as plt
import io
from PIL import Image
import plotly.express as px

C:\geographic_or_ds_playground\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
problem = SiteProblem()

problem.add_demand(
    pd.read_csv("demand_MF_50_84.csv"), demand_col="MF50-84", location_id_col="LSOA 2021 Name"
)

problem.add_region_geometry_layer(
    geopandas.read_file("LSOA_Devon_2021_EW_BSC_V4.gpkg"), common_col="LSOA21NM"
)

problem.add_equity_data("devon_imd_2025_2021_LSOAs.csv",
                        equity_col="Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOA",
                        common_col="LSOA name (2021)", disadvantaged_end="low", label="IMD Decile")

existing_cdcs = pd.read_csv("devon_cdcs.csv")
existing_cdcs_gdf =     geopandas.GeoDataFrame(
        existing_cdcs,  # Our pandas dataframe
        geometry=geopandas.points_from_xy(
            existing_cdcs[
                "Longitude"
            ],  # Our 'x' column (horizontal position of points)
            existing_cdcs["Latitude"],  # Our 'y' column (vertical position of points)
        ),
        crs="EPSG:4326",
    )

problem.add_sites(
        existing_cdcs_gdf,
        candidate_id_col="Facility_Name",
        required_sites_col="Existing"
    )

problem_car = problem.copy()

problem_car.add_travel_matrix(
    pd.read_csv("travel_matrix_car.csv"), unit="minutes", source_col="from_id"
)

# problem_car.add_additional_data(
#     pd.read_csv("travel_matrix_public_transport.csv").fillna(9999.0), common_col="from_id", label="Public Transport Travel Time (minutes)",
#     column_of_interest=""
# )

problem_pt = problem.copy()

problem_pt.add_travel_matrix(
    pd.read_csv("travel_matrix_public_transport.csv"), unit="minutes", source_col="from_id",
    allow_missing=True, treat_as_missing=9999,
)

# problem_pt.add_additional_data(
#     pd.read_csv("travel_matrix_car.csv").fillna(9999.0), common_col="from_id", label="Car Travel Time (minutes)"
# )

In [3]:
solutions_car = []

for i in range(4, 16):
    solutions_car.append({'n': i, 'solution': problem_car.solve(
        p=i,
        threshold_for_coverage=30,
        rank_on="proportion_demand_improved",
        baseline=True,
        meaningful_change_threshold=5.0,
        beyond_thresholds=[45, 60],
        n_jobs=-1,
    )})

  0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:06<00:00,  6.09s/it]

100%|██████████| 1/1 [00:06<00:00,  6.09s/it]

  0%|          | 0/14 [00:00<?, ?it/s]

  7%|▋         | 1/14 [00:10<02:15, 10.44s/it]

 79%|███████▊  | 11/14 [00:10<00:02,  1.42it/s]

100%|██████████| 14/14 [00:10<00:00,  1.31it/s]

  0%|          | 0/91 [00:00<?, ?it/s]

  2%|▏         | 2/91 [00:08<05:56,  4.00s/it]

100%|██████████| 91/91 [00:08<00:00, 11.37it/s]

  0%|          | 0/364 [00:00<?, ?it/s]

  1%|▏         | 5/364 [00:01<01:28,  4.04it/s]

  3%|▎         | 10/364 [00:01<00:41,  8.51it/s]

  4%|▍         | 15/364 [00:01<00:27, 12.60it/s]

 26%|██▌       | 95/364 [00:01<00:02, 100.78it/s]

 30%|███       | 110/364 [00:02<00:04, 55.48it/s]

 33%|███▎      | 120/364 [00:02<00:04, 55.23it/s]

 38%|███▊      | 140/364 [00:02<00:03, 67.59it/s]

 41%|████      | 150/364 [00:03<00:03, 67.76it/s]

 51%|█████     | 185/364 [00:03<00:02, 78.42it/s]

 56%|█████▋    | 205/364 [00:03<00:02, 70.73it/s]

 60%|██████    | 220/364 [00:04<00:02, 54.81it/s]

 67%|██████▋   | 245/364 [00:04<00:01, 74.80it/s]

 73%|███████▎  | 265/364 [00:04<00:01, 80.39it/s]

 82%|████████▏ | 300/364 [00:04<00:00, 108.08it/s]

 87%|████████▋ | 315/364 [00:04<00:00, 107.43it/s]

 92%|█████████▏| 335/364 [00:04<00:00, 122.53it/s]

100%|██████████| 364/364 [00:05<00:00, 72.40it/s]

  0%|          | 0/1001 [00:00<?, ?it/s]

  1%|▏         | 13/1001 [00:03<04:42,  3.49it/s]

  4%|▍         | 39/1001 [00:04<01:23, 11.46it/s]

 21%|██        | 208/1001 [00:04<00:10, 74.69it/s]

 27%|██▋       | 273/1001 [00:06<00:13, 52.37it/s]

 35%|███▌      | 351/1001 [00:07<00:09, 70.12it/s]

 43%|████▎     | 429/1001 [00:07<00:07, 79.95it/s]

 45%|████▌     | 455/1001 [00:08<00:06, 79.47it/s]

 47%|████▋     | 468/1001 [00:08<00:06, 79.98it/s]

 51%|█████     | 507/1001 [00:08<00:04, 102.28it/s]

 53%|█████▎    | 533/1001 [00:08<00:05, 88.32it/s]

 56%|█████▌    | 559/1001 [00:09<00:08, 54.61it/s]

 58%|█████▊    | 585/1001 [00:10<00:07, 54.07it/s]

 68%|██████▊   | 676/1001 [00:10<00:03, 107.66it/s]

 70%|███████   | 702/1001 [00:11<00:04, 72.91it/s]

 75%|███████▌  | 754/1001 [00:11<00:02, 82.61it/s]

 78%|███████▊  | 780/1001 [00:12<00:02, 78.17it/s]

 79%|███████▉  | 793/1001 [00:12<00:02, 71.42it/s]

 82%|████████▏ | 819/1001 [00:12<00:02, 82.76it/s]

 84%|████████▍ | 845/1001 [00:12<00:01, 91.01it/s]

 88%|████████▊ | 884/1001 [00:13<00:01, 90.40it/s]

 92%|█████████▏| 923/1001 [00:13<00:00, 106.15it/s]

 99%|█████████▊| 988/1001 [00:13<00:00, 155.72it/s]

100%|██████████| 1001/1001 [00:13<00:00, 72.14it/s]

  0%|          | 0/2002 [00:00<?, ?it/s]

  1%|▏         | 26/2002 [00:05<06:46,  4.86it/s]

  3%|▎         | 52/2002 [00:06<03:44,  8.67it/s]

  5%|▌         | 104/2002 [00:07<01:44, 18.24it/s]

  6%|▋         | 130/2002 [00:07<01:17, 24.13it/s]

  8%|▊         | 156/2002 [00:08<01:09, 26.71it/s]

 22%|██▏       | 442/2002 [00:09<00:11, 131.97it/s]

 27%|██▋       | 546/2002 [00:10<00:11, 121.80it/s]

 29%|██▊       | 572/2002 [00:12<00:22, 62.40it/s]

 31%|███       | 624/2002 [00:12<00:19, 70.08it/s]

 32%|███▏      | 650/2002 [00:13<00:21, 64.10it/s]

 39%|███▉      | 780/2002 [00:13<00:12, 101.31it/s]

 40%|████      | 806/2002 [00:14<00:14, 85.19it/s]

 42%|████▏     | 832/2002 [00:15<00:17, 66.03it/s]

 45%|████▌     | 910/2002 [00:16<00:14, 77.86it/s]

 48%|████▊     | 962/2002 [00:16<00:13, 79.98it/s]

 49%|████▉     | 988/2002 [00:16<00:11, 88.66it/s]

 53%|█████▎    | 1066/2002 [00:17<00:07, 124.99it/s]

 57%|█████▋    | 1144/2002 [00:18<00:09, 87.60it/s]

 58%|█████▊    | 1170/2002 [00:18<00:09, 88.30it/s]

 60%|█████▉    | 1196/2002 [00:19<00:09, 85.29it/s]

 64%|██████▎   | 1274/2002 [00:20<00:11, 65.39it/s]

 66%|██████▌   | 1326/2002 [00:22<00:14, 45.74it/s]

 69%|██████▉   | 1378/2002 [00:23<00:10, 58.12it/s]

 70%|███████   | 1404/2002 [00:23<00:12, 48.85it/s]

 78%|███████▊  | 1560/2002 [00:25<00:05, 81.43it/s]

 83%|████████▎ | 1664/2002 [00:25<00:03, 110.93it/s]

 86%|████████▌ | 1716/2002 [00:26<00:03, 80.89it/s]

 90%|████████▉ | 1794/2002 [00:27<00:02, 75.83it/s]

 91%|█████████ | 1820/2002 [00:28<00:02, 74.15it/s]

 95%|█████████▍| 1898/2002 [00:29<00:01, 70.52it/s]

100%|██████████| 2002/2002 [00:29<00:00, 111.37it/s]

100%|██████████| 2002/2002 [00:29<00:00, 67.59it/s]

  0%|          | 0/3003 [00:00<?, ?it/s]

  1%|▏         | 38/3003 [00:09<12:34,  3.93it/s]

  3%|▎         | 76/3003 [00:12<07:20,  6.64it/s]

  4%|▍         | 114/3003 [00:12<04:04, 11.82it/s]

  8%|▊         | 228/3003 [00:14<01:49, 25.25it/s]

 25%|██▌       | 760/3003 [00:14<00:16, 132.17it/s]

 30%|███       | 912/3003 [00:22<00:36, 56.76it/s]

 39%|███▉      | 1178/3003 [00:23<00:24, 74.81it/s]

 42%|████▏     | 1254/3003 [00:24<00:21, 82.59it/s]

 49%|████▉     | 1482/3003 [00:24<00:12, 119.18it/s]

 52%|█████▏    | 1558/3003 [00:25<00:13, 109.19it/s]

 53%|█████▎    | 1596/3003 [00:25<00:12, 117.19it/s]

 54%|█████▍    | 1634/3003 [00:26<00:14, 94.01it/s]

 56%|█████▌    | 1672/3003 [00:30<00:33, 39.79it/s]

 59%|█████▉    | 1786/3003 [00:31<00:21, 55.53it/s]

 62%|██████▏   | 1862/3003 [00:32<00:17, 63.61it/s]

 63%|██████▎   | 1900/3003 [00:32<00:15, 73.24it/s]

 68%|██████▊   | 2052/3003 [00:33<00:10, 89.95it/s]

 70%|██████▉   | 2090/3003 [00:34<00:10, 90.63it/s]

 73%|███████▎  | 2204/3003 [00:34<00:06, 125.14it/s]

 80%|███████▉  | 2394/3003 [00:36<00:06, 99.44it/s]

 81%|████████  | 2432/3003 [00:37<00:05, 107.95it/s]

 84%|████████▎ | 2508/3003 [00:39<00:07, 65.89it/s]

 89%|████████▊ | 2660/3003 [00:39<00:03, 102.04it/s]

 91%|█████████ | 2736/3003 [00:40<00:02, 122.67it/s]

 92%|█████████▏| 2774/3003 [00:40<00:01, 122.79it/s]

 94%|█████████▎| 2812/3003 [00:40<00:01, 123.94it/s]

 97%|█████████▋| 2926/3003 [00:41<00:00, 156.26it/s]

100%|█████████▉| 3002/3003 [00:41<00:00, 189.44it/s]

100%|██████████| 3003/3003 [00:41<00:00, 72.62it/s]

  0%|          | 0/3432 [00:00<?, ?it/s]

  1%|▏         | 43/3432 [00:11<14:36,  3.87it/s]

  3%|▎         | 86/3432 [00:11<06:20,  8.80it/s]

 16%|█▋        | 559/3432 [00:11<00:33, 86.13it/s]

 26%|██▋       | 903/3432 [00:17<00:33, 75.02it/s]

 29%|██▉       | 989/3432 [00:19<00:39, 62.45it/s]

 33%|███▎      | 1118/3432 [00:21<00:33, 68.84it/s]

 36%|███▋      | 1247/3432 [00:21<00:24, 89.93it/s]

 40%|████      | 1376/3432 [00:22<00:22, 91.08it/s]

 45%|████▌     | 1548/3432 [00:23<00:15, 124.74it/s]

 48%|████▊     | 1634/3432 [00:23<00:15, 116.77it/s]

 51%|█████▏    | 1763/3432 [00:29<00:32, 51.74it/s]

 55%|█████▌    | 1892/3432 [00:30<00:24, 63.37it/s]

 58%|█████▊    | 1978/3432 [00:31<00:21, 66.25it/s]

 61%|██████▏   | 2107/3432 [00:33<00:17, 73.88it/s]

 69%|██████▉   | 2365/3432 [00:34<00:10, 103.86it/s]

 70%|███████   | 2408/3432 [00:34<00:09, 108.44it/s]

 73%|███████▎  | 2494/3432 [00:35<00:08, 111.75it/s]

 74%|███████▍  | 2537/3432 [00:35<00:07, 117.25it/s]

 75%|███████▌  | 2580/3432 [00:35<00:06, 128.86it/s]

 76%|███████▋  | 2623/3432 [00:37<00:12, 64.13it/s]

 78%|███████▊  | 2666/3432 [00:39<00:14, 54.19it/s]

 80%|████████  | 2752/3432 [00:41<00:14, 45.69it/s]

 83%|████████▎ | 2838/3432 [00:41<00:08, 67.55it/s]

 89%|████████▉ | 3053/3432 [00:42<00:03, 104.38it/s]

 90%|█████████ | 3096/3432 [00:43<00:03, 107.60it/s]

 91%|█████████▏| 3139/3432 [00:43<00:02, 119.96it/s]

 94%|█████████▍| 3225/3432 [00:43<00:01, 127.64it/s]

 95%|█████████▌| 3268/3432 [00:44<00:01, 136.40it/s]

 96%|█████████▋| 3311/3432 [00:44<00:01, 105.26it/s]

 99%|█████████▉| 3397/3432 [00:45<00:00, 136.04it/s]

100%|██████████| 3432/3432 [00:45<00:00, 75.87it/s]

  0%|          | 0/3003 [00:00<?, ?it/s]

  1%|▏         | 38/3003 [00:09<11:59,  4.12it/s]

  3%|▎         | 76/3003 [00:10<05:34,  8.75it/s]

 11%|█▏        | 342/3003 [00:10<00:47, 55.80it/s]

 15%|█▌        | 456/3003 [00:11<00:34, 74.11it/s]

 27%|██▋       | 798/3003 [00:16<00:31, 70.14it/s]

 28%|██▊       | 836/3003 [00:18<00:39, 55.27it/s]

 29%|██▉       | 874/3003 [00:19<00:41, 51.02it/s]

 38%|███▊      | 1140/3003 [00:20<00:21, 85.75it/s]

 39%|███▉      | 1178/3003 [00:20<00:20, 91.09it/s]

 40%|████      | 1216/3003 [00:21<00:20, 85.15it/s]

 52%|█████▏    | 1558/3003 [00:25<00:17, 82.97it/s]

 53%|█████▎    | 1596/3003 [00:27<00:20, 69.37it/s]

 54%|█████▍    | 1634/3003 [00:27<00:18, 73.83it/s]

 56%|█████▌    | 1672/3003 [00:28<00:18, 72.95it/s]

 58%|█████▊    | 1748/3003 [00:29<00:17, 73.55it/s]

 61%|██████    | 1824/3003 [00:29<00:14, 83.94it/s]

 66%|██████▌   | 1976/3003 [00:30<00:09, 107.03it/s]

 70%|██████▉   | 2090/3003 [00:31<00:08, 108.32it/s]

 77%|███████▋  | 2318/3003 [00:34<00:07, 95.11it/s]

 80%|███████▉  | 2394/3003 [00:37<00:09, 65.51it/s]

 82%|████████▏ | 2470/3003 [00:37<00:06, 79.89it/s]

 84%|████████▎ | 2508/3003 [00:37<00:05, 85.01it/s]

 87%|████████▋ | 2622/3003 [00:37<00:03, 124.19it/s]

 89%|████████▊ | 2660/3003 [00:38<00:03, 107.84it/s]

 91%|█████████ | 2736/3003 [00:38<00:02, 123.55it/s]

 96%|█████████▌| 2888/3003 [00:39<00:00, 184.62it/s]

 99%|█████████▊| 2964/3003 [00:39<00:00, 220.48it/s]

100%|█████████▉| 3002/3003 [00:39<00:00, 232.82it/s]

100%|██████████| 3003/3003 [00:39<00:00, 76.35it/s]

  0%|          | 0/2002 [00:00<?, ?it/s]

  1%|▏         | 26/2002 [00:04<05:39,  5.83it/s]

  4%|▍         | 78/2002 [00:04<01:29, 21.50it/s]

  5%|▌         | 104/2002 [00:05<01:25, 22.20it/s]

  8%|▊         | 156/2002 [00:06<01:03, 29.06it/s]

 14%|█▍        | 286/2002 [00:07<00:25, 68.15it/s]

 26%|██▌       | 520/2002 [00:07<00:08, 171.17it/s]

 31%|███       | 624/2002 [00:11<00:21, 62.65it/s]

 35%|███▌      | 702/2002 [00:12<00:19, 68.16it/s]

 38%|███▊      | 754/2002 [00:13<00:18, 67.63it/s]

 43%|████▎     | 858/2002 [00:14<00:14, 78.88it/s]

 49%|████▉     | 988/2002 [00:14<00:08, 114.54it/s]

 52%|█████▏    | 1040/2002 [00:15<00:08, 110.85it/s]

 55%|█████▍    | 1092/2002 [00:16<00:09, 94.88it/s]

 56%|█████▌    | 1118/2002 [00:16<00:09, 97.53it/s]

 57%|█████▋    | 1144/2002 [00:16<00:11, 77.07it/s]

 58%|█████▊    | 1170/2002 [00:17<00:12, 67.14it/s]

 61%|██████    | 1222/2002 [00:17<00:09, 82.00it/s]

 66%|██████▌   | 1326/2002 [00:18<00:05, 129.20it/s]

 68%|██████▊   | 1352/2002 [00:19<00:07, 84.55it/s]

 69%|██████▉   | 1378/2002 [00:19<00:06, 92.79it/s]

 73%|███████▎  | 1456/2002 [00:19<00:03, 139.44it/s]

 74%|███████▍  | 1482/2002 [00:19<00:03, 147.60it/s]

 75%|███████▌  | 1508/2002 [00:20<00:05, 92.72it/s]

 77%|███████▋  | 1534/2002 [00:20<00:04, 105.97it/s]

 78%|███████▊  | 1560/2002 [00:21<00:06, 63.15it/s]

 79%|███████▉  | 1586/2002 [00:21<00:06, 66.30it/s]

 81%|████████  | 1612/2002 [00:22<00:05, 70.21it/s]

 84%|████████▍ | 1690/2002 [00:22<00:03, 85.11it/s]

 87%|████████▋ | 1742/2002 [00:23<00:02, 107.01it/s]

 88%|████████▊ | 1768/2002 [00:23<00:02, 89.67it/s]

 92%|█████████▏| 1846/2002 [00:23<00:01, 132.26it/s]

 95%|█████████▍| 1898/2002 [00:23<00:00, 162.66it/s]

 97%|█████████▋| 1950/2002 [00:24<00:00, 177.92it/s]

100%|██████████| 2002/2002 [00:24<00:00, 82.59it/s]

  0%|          | 0/1001 [00:00<?, ?it/s]

  1%|▏         | 13/1001 [00:02<02:59,  5.49it/s]

  3%|▎         | 26/1001 [00:03<02:04,  7.86it/s]

 21%|██        | 208/1001 [00:03<00:09, 82.93it/s]

 27%|██▋       | 273/1001 [00:04<00:09, 77.81it/s]

 30%|██▉       | 299/1001 [00:05<00:10, 63.91it/s]

 34%|███▍      | 338/1001 [00:06<00:12, 54.29it/s]

 39%|███▉      | 390/1001 [00:06<00:08, 74.09it/s]

 42%|████▏     | 416/1001 [00:07<00:09, 63.26it/s]

 48%|████▊     | 481/1001 [00:07<00:05, 97.40it/s]

 53%|█████▎    | 533/1001 [00:07<00:03, 122.15it/s]

 56%|█████▌    | 559/1001 [00:09<00:07, 57.61it/s]

 62%|██████▏   | 624/1001 [00:10<00:05, 66.37it/s]

 66%|██████▌   | 663/1001 [00:10<00:05, 61.83it/s]

 71%|███████▏  | 715/1001 [00:11<00:03, 80.19it/s]

 74%|███████▍  | 741/1001 [00:11<00:03, 79.86it/s]

 79%|███████▉  | 793/1001 [00:11<00:02, 98.31it/s]

 82%|████████▏ | 819/1001 [00:12<00:02, 74.97it/s]

 87%|████████▋ | 871/1001 [00:12<00:01, 106.69it/s]

 90%|████████▉ | 897/1001 [00:13<00:01, 88.05it/s]

 92%|█████████▏| 923/1001 [00:13<00:00, 96.45it/s]

 96%|█████████▌| 962/1001 [00:13<00:00, 113.59it/s]

 99%|█████████▊| 988/1001 [00:13<00:00, 125.81it/s]

100%|██████████| 1001/1001 [00:13<00:00, 73.49it/s]

  0%|          | 0/364 [00:00<?, ?it/s]

  1%|▏         | 5/364 [00:00<00:59,  6.07it/s]

  3%|▎         | 10/364 [00:01<00:35, 10.09it/s]

  5%|▌         | 20/364 [00:01<00:16, 21.22it/s]

  8%|▊         | 30/364 [00:01<00:10, 31.30it/s]

 16%|█▋        | 60/364 [00:01<00:05, 52.33it/s]

 29%|██▉       | 105/364 [00:02<00:03, 71.27it/s]

 38%|███▊      | 140/364 [00:02<00:03, 68.05it/s]

 48%|████▊     | 175/364 [00:02<00:02, 87.99it/s]

 56%|█████▋    | 205/364 [00:04<00:03, 45.66it/s]

 73%|███████▎  | 265/364 [00:04<00:01, 78.22it/s]

 91%|█████████ | 330/364 [00:05<00:00, 87.05it/s]

100%|██████████| 364/364 [00:05<00:00, 70.38it/s]

### Compare with best results for 1, 2 and 3 sites

We have to set these up slightly differently because this version of lokigi can't handle p being < number of sites marked as 'required'.

In [4]:
problem_car_simple = problem_car.copy()

problem_car_simple.add_sites(
        existing_cdcs_gdf[existing_cdcs_gdf["Existing"]=="Yes"],
        candidate_id_col="Facility_Name",
    )

problem_pt_simple = problem_pt.copy()

problem_pt_simple.add_sites(
        existing_cdcs_gdf[existing_cdcs_gdf["Existing"]=="Yes"],
        candidate_id_col="Facility_Name",
    )

In [5]:
solution_1_car = problem_car_simple.solve(p=1, threshold_for_coverage=30)
solution_2_car = problem_car_simple.solve(p=2, threshold_for_coverage=30)
solution_3_car = problem_car_simple.solve(p=3, threshold_for_coverage=30)

  0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 4/4 [00:00<00:00, 16.46it/s]

100%|██████████| 4/4 [00:00<00:00, 16.40it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 14.32it/s]

100%|██████████| 6/6 [00:00<00:00, 14.27it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 4/4 [00:00<00:00, 15.08it/s]

100%|██████████| 4/4 [00:00<00:00, 14.95it/s]

In [6]:
solutions_car.append({'n': 1, 'solution':solution_1_car})
solutions_car.append({'n': 2, 'solution':solution_2_car})
solutions_car.append({'n': 3, 'solution':solution_3_car})

# Compare best

In [7]:
result_df_comparison = []

for sol in solutions_car:
    result_df_comparison.append(sol['solution'].return_best_combination_details(top_n=1))

result_df_comparison = pd.concat(result_df_comparison)
result_df_comparison['n'] = result_df_comparison['site_indices'].apply(lambda x: len(x))
result_df_comparison

,index,solution_rank,site_names,site_indices,unselected_site_names,coverage_threshold,weighted_average,unweighted_average,90th_percentile,max,...,sites_added_vs_baseline,demand_beyond_threshold_45,regions_beyond_threshold_45,demand_beyond_threshold_45_by_equity_group,regions_beyond_threshold_45_by_equity_group,demand_beyond_threshold_60,regions_beyond_threshold_60,demand_beyond_threshold_60_by_equity_group,regions_beyond_threshold_60_by_equity_group,n
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,23.392076,21.421445,42.396666,61.533333,...,[],52145.0,58.0,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 16403.0, 5...","{1: 1, 2: 2, 3: 3, 4: 17, 5: 19, 6: 8, 7: 5, 8...",2049.0,2.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ...",4
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 8]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.147958,20.206196,42.073333,61.183334,...,[Newton Abbott - Market Walk],49306.0,55.0,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 16403.0, 5...","{1: 1, 2: 2, 3: 3, 4: 17, 5: 17, 6: 8, 7: 4, 8...",942.0,1.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ...",5
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 8, 12]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,20.689798,18.811545,38.690000,61.183334,...,"[Newton Abbott - Market Walk, Barnstaple - Arc...",36959.0,40.0,"{1: 0.0, 2: 0.0, 3: 1893.0, 4: 10068.0, 5: 124...","{1: 0, 2: 0, 3: 2, 4: 11, 5: 14, 6: 6, 7: 4, 8...",942.0,1.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ...",6
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 8, 12, 17]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,19.744424,17.906516,37.170000,61.183334,...,"[Newton Abbott - Market Walk, Barnstaple - Arc...",32446.0,36.0,"{1: 0.0, 2: 0.0, 3: 1893.0, 4: 10068.0, 5: 885...","{1: 0, 2: 0, 3: 2, 4: 11, 5: 11, 6: 6, 7: 3, 8...",942.0,1.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ...",7
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 8, 10, 12, 17]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,18.674391,16.994810,33.549999,61.183334,...,"[Newton Abbott - Market Walk, Honiton - Devons...",22237.0,24.0,"{1: 0.0, 2: 0.0, 3: 1893.0, 4: 9359.0, 5: 5991...","{1: 0, 2: 0, 3: 2, 4: 10, 5: 7, 6: 4, 7: 1, 8:...",942.0,1.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ...",8
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4, 8, 10, 12, 17]","[Okehampton - Exeter Road Industrial Estate, C...",30,17.609237,16.055578,29.900000,61.183334,...,"[Tiverton - Lowman Way, Newton Abbott - Market...",18435.0,20.0,"{1: 0.0, 2: 0.0, 3: 982.0, 4: 9359.0, 5: 4186....","{1: 0, 2: 0, 3: 1, 4: 10, 5: 5, 6: 3, 7: 1, 8:...",942.0,1.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ...",9
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4, 8, 10, 12, 15, 17]","[Okehampton - Exeter Road Industrial Estate, C...",30,16.501467,15.173548,28.583334,53.633335,...,"[Tiverton - Lowman Way, Newton Abbott - Market...",9521.0,10.0,"{1: 0.0, 2: 0.0, 3: 982.0, 4: 2909.0, 5: 1722....","{1: 0, 2: 0, 3: 1, 4: 3, 5: 2, 6: 3, 7: 1, 8: ...",0.0,0.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0....","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: ...",10
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4, 8, 10, 11, 12, 15, 17]","[Okehampton - Exeter Road Industrial Estate, C...",30,15.848246,14.603292,28.583334,53.633335,...,"[Tiverton - Lowman Way, Newton Abbott - Market...",9521.0,10.0,"{1: 0.0, 2: 0.0, 3: 982.0, 4: 2909.0, 5: 1722....","{1: 0, 2: 0, 3: 1, 4: 3, 5: 2, 6: 3, 7: 1, 8: ...",0.0,0.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0....","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: ...",11
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4, 5, 8, 10, 11, 12, 15, 17]","[Crediton - Lords Meadow, South Molton - Pathf...",30,15.037106,13.970142,27.423333,53.633335,...,"[Tiverton - Lowman Way, Okehampton - Exeter Ro...",5827.0,6.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 1079.0, 5: 840.0, ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 1, 6: 3, 7: 1, 8: ...",0.0,0.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0....","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: ...",12
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4, 5, 8, 10, 11, 12, 14, 15, 17]","[Crediton - Lords Meadow, South Molton - Pathf...",30,14.188906,13.360517,25.553334,45.966667,...,"[Tiverton - Lowman Way, Okehampton - Exeter Ro...",1079.0,1.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 1079.0, 5: 0.0, 6:...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ...",0.0,0.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0....","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: ...",13
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4, 8, 9, 10, 11, 12, 14, 15, 16, 17]","[Okehampton - Exeter Road Industrial Estate, C...",30,14.075811,13.282716,25.593334,45.933334,...,"[Tiverton - Lowman Way, Newton Abbott - Market...",882.0,1.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 882.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 0, 5: 1, 6: 0, 7: 0, 8: ...",0.0,0.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0....","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: ...",14
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 14, 15, 1...","[Crediton - Lords Meadow, South Molton - Pathf...",30,13.527050,12.843827,24.650000,38.850000,...,"[Tiverton - Lowman Way, Okehampton - Exeter Ro...",0.0,0.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0....","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: ...",0.0,0.0,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0....","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: ...",15
0,0,1,[NHS Nightingale Exeter],[1],"[Bideford Community Hospital, Colin Campbell C...",30,50.465206,49.931230,81.836666,113.850000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
0,0,1,"[NHS Nightingale Exeter, Colin Campbell Court,...","[1, 2]","[Bideford Community Hospital, Torbay & South D...",30,37.051850,34.235962,78.556669,113.850000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
0,0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2]",[Torbay & South Devon Community Diagnostic Cen...,30,28.389413,26.459991,46.653334,67.850000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [8]:
result_df_comparison.to_pickle("comparison_num_sites.pkl")

In [9]:
px.bar(result_df_comparison, x="n", y="weighted_average")

In [10]:
px.bar(result_df_comparison, x="n", y="max")

In [11]:
px.bar(result_df_comparison, x="n", y="90th_percentile")

## Explore solutions

In [12]:
solution_car_5 = [i for i in solutions_car if i["n"] == 5][0]['solution']

In [13]:
solution_car_5.show_solutions()

,solution_rank,site_names,site_indices,unselected_site_names,coverage_threshold,weighted_average,unweighted_average,90th_percentile,max,weighted_average_for_ranking,...,sites_closed_vs_baseline,sites_added_vs_baseline,demand_beyond_threshold_45,regions_beyond_threshold_45,demand_beyond_threshold_45_by_equity_group,regions_beyond_threshold_45_by_equity_group,demand_beyond_threshold_60,regions_beyond_threshold_60,demand_beyond_threshold_60_by_equity_group,regions_beyond_threshold_60_by_equity_group
0,1,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 8]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.15,20.21,42.07,61.18,22.15,...,[],[Newton Abbott - Market Walk],49306.0,55,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 16403.0, 5...","{1: 1, 2: 2, 3: 3, 4: 17, 5: 17, 6: 8, 7: 4, 8...",942.0,1,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ..."
1,2,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 17]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.26,20.37,41.91,61.18,22.26,...,[],[Paignton - Hyde Road],45487.0,52,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 16403.0, 5...","{1: 1, 2: 2, 3: 3, 4: 17, 5: 15, 6: 8, 7: 3, 8...",942.0,1,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ..."
2,3,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 12]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,21.93,20.03,39.41,61.53,21.93,...,[],[Barnstaple - Archwood Retail Park],39798.0,43,"{1: 0.0, 2: 0.0, 3: 1893.0, 4: 10068.0, 5: 142...","{1: 0, 2: 0, 3: 2, 4: 11, 5: 16, 6: 6, 7: 5, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."
3,4,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 9]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.26,20.38,41.27,61.53,22.26,...,[],[Bovey Tracey - Blue Waters],46019.0,51,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 13656.0, 5...","{1: 1, 2: 2, 3: 3, 4: 14, 5: 15, 6: 8, 7: 5, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."
4,5,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 10]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.32,20.51,39.44,61.53,22.32,...,[],[Honiton - Devonshire Road],41936.0,46,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 15694.0, 5...","{1: 1, 2: 2, 3: 3, 4: 16, 5: 15, 6: 6, 7: 3, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."
5,6,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 4]","[Okehampton - Exeter Road Industrial Estate, C...",30,22.19,20.39,41.07,61.53,22.19,...,[],[Tiverton - Lowman Way],44511.0,51,"{1: 658.0, 2: 1169.0, 3: 1491.0, 4: 12571.0, 5...","{1: 1, 2: 2, 3: 2, 4: 14, 5: 17, 6: 7, 7: 5, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."
6,7,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 5]","[Tiverton - Lowman Way, Crediton - Lords Meado...",30,22.05,20.37,37.61,61.53,22.05,...,[],[Okehampton - Exeter Road Industrial Estate],34564.0,39,"{1: 658.0, 2: 1169.0, 3: 509.0, 4: 6816.0, 5: ...","{1: 1, 2: 2, 3: 1, 4: 7, 5: 13, 6: 7, 7: 5, 8:...",1107.0,1,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 11...","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 1, 7: 0, 8: ..."
7,8,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 7]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.42,20.69,39.84,61.53,22.42,...,[],[South Molton - Pathfields],35114.0,38,"{1: 0.0, 2: 0.0, 3: 982.0, 4: 10068.0, 5: 1157...","{1: 0, 2: 0, 3: 1, 4: 11, 5: 13, 6: 5, 7: 5, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."
8,9,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 6]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.45,20.66,39.55,61.53,22.45,...,[],[Crediton - Lords Meadow],40606.0,46,"{1: 658.0, 2: 1169.0, 3: 1491.0, 4: 11030.0, 5...","{1: 1, 2: 2, 3: 2, 4: 12, 5: 14, 6: 7, 7: 5, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."
9,10,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 15]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.28,20.54,39.94,61.53,22.28,...,[],[Tavistock - Drake Road],43231.0,48,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 9953.0, 5:...","{1: 1, 2: 2, 3: 3, 4: 10, 5: 16, 6: 8, 7: 5, 8...",1107.0,1,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 11...","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 1, 7: 0, 8: ..."
10,11,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 14]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.28,20.60,39.47,61.18,22.28,...,[],[Kingsbridge - Fore Street],40739.0,47,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 16403.0, 5...","{1: 1, 2: 2, 3: 3, 4: 17, 5: 14, 6: 5, 7: 2, 8...",942.0,1,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: ..."
11,12,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 11]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.74,20.85,42.40,61.53,22.74,...,[],[Exmouth - The Strand],52145.0,58,"{1: 658.0, 2: 1169.0, 3: 2402.0, 4: 16403.0, 5...","{1: 1, 2: 2, 3: 3, 4: 17, 5: 19, 6: 8, 7: 5, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."
12,13,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 16]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.61,20.84,39.84,61.53,22.61,...,[],[Holsworthy - Underlane],42192.0,47,"{1: 658.0, 2: 1169.0, 3: 1420.0, 4: 8914.0, 5:...","{1: 1, 2: 2, 3: 2, 4: 9, 5: 17, 6: 8, 7: 5, 8:...",1107.0,1,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 11...","{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 1, 7: 0, 8: ..."
13,14,"[Bideford Community Hospital, NHS Nightingale ...","[0, 1, 2, 3, 13]","[Tiverton - Lowman Way, Okehampton - Exeter Ro...",30,22.49,20.51,39.84,61.53,22.49,...,[],[Ilfracombe - Wilder Road],43630.0,46,"{1: 0.0, 2: 0.0, 3: 1893.0, 4: 13900.0, 5: 142...","{1: 0, 2: 0, 3: 2, 4: 14, 5: 16, 6: 6, 7: 5, 8...",2049.0,2,"{1: 0.0, 2: 0.0, 3: 0.0, 4: 942.0, 5: 0.0, 6: ...","{1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 1, 7: 0, 8: ..."

In [14]:
solution_car_5.show_solutions_colnames()

Index(['solution_rank', 'site_names', 'site_indices', 'unselected_site_names',
       'coverage_threshold', 'weighted_average', 'unweighted_average',
       '90th_percentile', 'max', 'weighted_average_for_ranking',
       'unweighted_average_for_ranking', 'max_for_ranking', 'total_cost',
       'proportion_within_coverage_threshold',
       'proportion_regions_within_coverage_threshold',
       'demand_within_coverage_threshold', 'regions_within_coverage_threshold',
       'regions_unreachable', 'demand_unreachable',
       'proportion_demand_unreachable', 'weighted_by_equity_group',
       'unweighted_by_equity_group', 'coverage_by_equity_group',
       'coverage_regions_by_equity_group', 'max_cost_by_equity_group',
       'regions_unreachable_by_equity_group',
       'demand_unreachable_by_equity_group', 'gap_absolute_weighted',
       'gap_relative_weighted', 'avg_lower_third_bins',
       'avg_middle_third_bins', 'avg_upper_third_bins', 'inter_tertile_ratio',
       'gap_absolute_description', 'gap_relative_description',
       'inter_tertile_description', 'problem_df', 'additional_site_names',
       'demand_improved', 'demand_worsened', 'demand_unchanged',
       'proportion_demand_improved', 'proportion_demand_worsened',
       'regions_improved', 'regions_worsened', 'regions_unchanged',
       'mean_reduction_among_improved', 'mean_increase_among_worsened',
       'max_reduction', 'max_increase', 'demand_improved_by_equity_group',
       'demand_worsened_by_equity_group', 'sites_closed_vs_baseline',
       'sites_added_vs_baseline', 'demand_beyond_threshold_45',
       'regions_beyond_threshold_45',
       'demand_beyond_threshold_45_by_equity_group',
       'regions_beyond_threshold_45_by_equity_group',
       'demand_beyond_threshold_60', 'regions_beyond_threshold_60',
       'demand_beyond_threshold_60_by_equity_group',
       'regions_beyond_threshold_60_by_equity_group'],
      dtype='str')

## Solution Outputs

In [15]:
solution_car_5 = [i for i in solutions_car if i["n"] == 5][0]['solution']

In [16]:
solution_car_5

In [17]:
with open("solution_car_5.pkl", "wb") as f:
    pickle.dump(solution_car_5, f)

In [18]:
solution_car_5.solution_df.to_pickle("solution_car_5_solution_df.pkl")

In [19]:
def generate_solution_animation(solution, output_filename, frame_duration=0.5):

    frames = []

    total_n_solutions = len(solution.solution_df)

    # Get existing sites
    sites = solution.site_problem.show_sites()
    existing_sites = sites[sites[solution.site_problem._candidate_sites_required_sites_col]=="Yes"][solution.site_problem._candidate_sites_candidate_id_col].to_list()

    for i in range(1, total_n_solutions + 1):
        # Work out which the one additional site is
        sites_in_solution = solution.solution_df[solution.solution_df["solution_rank"]==i]["site_names"].iloc[0]
        new_site = [i for i in sites_in_solution if i not in existing_sites]
        ax = solution.plot_best_combination(solution_rank=i, title=f"Trying out {new_site[0]}\n(Option {i} of {total_n_solutions})")
        fig = ax.figure

        buffer = io.BytesIO()
        fig.savefig(buffer, format="png", bbox_inches="tight")
        buffer.seek(0)

        frames.append(Image.open(buffer).copy())

        plt.close(fig)

    frames[0].save(
        f"{output_filename}.gif",
        save_all=True,
        append_images=frames[1:],
        duration=int(frame_duration * 1000),
        loop=0,
    )

In [20]:
solution_car_6 = [i for i in solutions_car if i["n"] == 6][0]['solution']

In [21]:
with open("solution_car_6.pkl", "wb") as f:
    pickle.dump(solution_car_6, f)

In [22]:
solution_car_6.solution_df.to_pickle("solution_car_6_solution_df.pkl")

## Animation Generation

In [23]:
generate_solution_animation(solution_car_5, output_filename="solution_car_5", frame_duration=0.8)

In [24]:
generate_solution_animation(solution_car_6, output_filename="solution_car_6", frame_duration=0.2)

In [25]:
# solution_car_7 = [i for i in solutions_car if i["n"] == 7][0]['solution']
# generate_solution_animation(solution_car_7, output_filename="solution_car_7", frame_duration=0.1)

In [26]:
# solution_car_8 = [i for i in solutions_car if i["n"] == 8][0]['solution']
# generate_solution_animation(solution_car_8, output_filename="solution_car_8", frame_duration=0.05)

In [27]:
# solution_car_6.solution_df.head(10).to_pickle("solution_car_6_best.pkl")
# solution_car_7.solution_df.head(10).to_pickle("solution_car_7_best.pkl")
# solution_car_8.solution_df.head(10).to_pickle("solution_car_8_best.pkl")

In [28]:
# solution_car_6.solution_df.tail(1).to_pickle("solution_car_6_worst.pkl")
# solution_car_7.solution_df.tail(1).to_pickle("solution_car_7_worst.pkl")
# solution_car_8.solution_df.tail(1).to_pickle("solution_car_8_worst.pkl")